SELECT RESTAURANTE.NOME, RECEITA.NOME, PESSOA.NOME
FROM ((((AVALIACAO
INNER JOIN DEGUSTADOR ON AVALIACAO.CPF = DEGUSTADOR.CPF)
INNER JOIN RECEITA ON RECEITA.CODIGO = AVALIACAO.CODIGO)
INNER JOIN RESTAURANTE ON RESTAURANTE.CNPJ = AVALIACAO.CNPJ)
INNER JOIN PESSOA ON PESSOA.CPF = AVALIACAO.CPF)
WHERE NOTA > 9
